version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: salma
      MYSQL_DATABASE: users
      MYSQL_USER: salma
      MYSQL_PASSWORD: salma
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
