spring:
  application:
    name: gateway-microservice
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: ${ROUTES_USER_AUTH_ID}
          uri: ${ROUTES_USER_AUTH_URI}
          predicates:
            - Path=/api/**
        - id: ${ROUTES_PROJECT_ID}
          uri: ${ROUTES_PROJECT_URI}
          predicates:
            - Path=/project/**
server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true